import { Metadata } from "next"
import './globals.css'
import { TheHeader } from "@/components/TheHeader"
import { TheFooter } from "@/components/TheFooter"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <TheHeader />
        <!-- Google tag (gtag.js) -->
            <script async src="https://www.googletagmanager.com/gtag/js?id=G-HN8G5B01H4"></script>
            <script>
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
            
              gtag('config', 'G-HN8G5B01H4');
            </script>
        <main className="container">{children}</main> 
        <TheFooter />
       </body>
    </html>
  )
}
